name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build production
    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: |
        npm install
        npx webpack --mode=production

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: web-activity-plugin
        path: dist
